# Generated by Django 3.1.4 on 2025-03-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('purchase_return', 'purchase_return'), ('purchase', 'purchase'), ('store_sell', 'store_sell'), ('ecommerce_sell', 'ecommerce_sell'), ('ecommerce_return', 'ecommerce_return'), ('transferred_in', 'transferred_in'), ('transferred_out', 'transferred_out'), ('stock_in', 'stock_in'), ('stock_out', 'stock_out'), ('adjustment', 'adjustment')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('invoice_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configure.country')),
            ],
            options={
                'db_table': 'stock_histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
