# Generated by Django 4.2.11 on 2024-09-13 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0010_alter_store_id_alter_storepaymentmethod_id'),
        ('product', '0016_alter_productunit_id_alter_productvariant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configure', '0011_alter_allusedcoupon_id_alter_banner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configure.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('purchase_return', 'purchase_return'), ('purchase', 'purchase'), ('store_sell', 'store_sell'), ('ecommerce_sell', 'ecommerce_sell'), ('ecommerce_return', 'ecommerce_return'), ('transferred_in', 'transferred_in'), ('transferred_out', 'transferred_out'), ('stock_in', 'stock_in'), ('stock_out', 'stock_out'), ('adjustment', 'adjustment')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('invoice_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configure.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='stock_histo_created_7eccf5_idx'), models.Index(fields=['type'], name='stock_histo_type_ffb87d_idx'), models.Index(fields=['invoice_no'], name='stock_histo_invoice_6476e6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['-created_at'], name='stocks_created_4b4953_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store', 'product_variant', 'country')},
        ),
    ]
