# Generated by Django 3.1.4 on 2025-03-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20250305_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='status',
        ),
    ]
