# Generated by Django 3.1.4 on 2024-09-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_delete_cartitem'),
        ('wishlist', '0002_auto_20240913_1018'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wishlist',
            name='wishlist_user_id_2af636_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('product_variant',)},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
