version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./tecgen:/app/tecgen
    command: bash -c "cd tecgen && python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./tecgen/nginx:/etc/nginx/conf.d
      - ./tecgen/static:/app/tecgen/static
    depends_on:
      - "app"

volumes:
  static: