# Generated by Django 4.2.11 on 2024-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='discount_type',
            field=models.CharField(choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignmember',
            name='discount_type',
            field=models.CharField(choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dealoftheweek',
            name='discount_type',
            field=models.CharField(choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], max_length=12),
        ),
    ]
