# Generated by Django 4.2.11 on 2024-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='online_discount',
            field=models.FloatField(default=0),
        ),
    ]
