# Generated by Django 3.1.4 on 2024-09-19 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('shown_in_website', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('logo', models.FileField(blank=True, null=True, upload_to='images')),
                ('cover_photo', models.FileField(blank=True, null=True, upload_to='images')),
                ('bio', models.CharField(max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('policies', models.TextField(blank=True, null=True)),
                ('off_days', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stores', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorePaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('cash', 'cash'), ('bank', 'Bank'), ('card', 'card'), ('mobile_bank', 'mobile_bank'), ('online', 'online')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_storepaymentmethods', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_storepaymentmethods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
