# Generated by Django 3.1.4 on 2024-09-19 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_number', models.SlugField(max_length=200, unique=True)),
                ('payment_method', models.CharField(choices=[('ssl_ecommerce', 'ssl_ecommerce'), ('aamarpay', 'aamarpay')], max_length=15)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('valid', 'valid'), ('cancelled', 'cancelled'), ('unattempted', 'unattempted'), ('failed', 'failed'), ('successful', 'successful'), ('expired', 'expired')], max_length=15)),
                ('has_hit_ipn', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_onlinepayments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_onlinepayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'online_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.FloatField(default=0)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('cash', 'cash'), ('bank', 'Bank'), ('card', 'card'), ('mobile_bank', 'mobile_bank'), ('online', 'online')], max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_orderpaymentmodels', to=settings.AUTH_USER_MODEL)),
                ('online_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.onlinepayment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_orderpaymentmodels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['-created_at'], name='online_paym_created_8e7797_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['status'], name='online_paym_status_c8aeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['payment_method'], name='online_paym_payment_a3a4d2_idx'),
        ),
    ]
