# Generated by Django 3.1.4 on 2025-03-05 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20250305_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_orderpaymentmodels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='online_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.onlinepayment'),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_orderpaymentmodels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_onlinepayments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_onlinepayments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['-created_at'], name='online_paym_created_8e7797_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['status'], name='online_paym_status_c8aeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['payment_method'], name='online_paym_payment_a3a4d2_idx'),
        ),
    ]
