# Generated by Django 4.2.11 on 2024-08-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['-created_at'], name='online_paym_created_8e7797_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['status'], name='online_paym_status_c8aeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['payment_method'], name='online_paym_payment_a3a4d2_idx'),
        ),
    ]
