# Generated by Django 4.2.11 on 2024-10-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
