# Generated by Django 4.2.11 on 2024-08-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariant_online_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'flat'), ('percentage', 'percentage')], default='SELECT', max_length=500),
        ),
    ]
