# Generated by Django 4.2.11 on 2024-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productvariant_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_type',
            field=models.CharField(choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], default='select', max_length=500),
        ),
    ]
