# Generated by Django 4.2.11 on 2024-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productvariant_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='promo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
