# Generated by Django 3.1.4 on 2024-09-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20240913_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
