# Generated by Django 4.2.11 on 2024-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=500, unique=True)),
                ('delivery_method', models.CharField(choices=[('home_delivery', 'home_delivery'), ('store_pickup', 'store_pickup'), ('store_sale', 'store_sale')], default='home_delivery', max_length=100)),
                ('payment_status', models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('due', 'due')], default='unpaid', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('on_process', 'on_process'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('payment_type', models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('online_payment', 'online_payment')], default='cash_on_delivery', max_length=30)),
                ('receiver_name', models.CharField(blank=True, max_length=500, null=True)),
                ('receiver_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('items_total_discount', models.FloatField(default=0)),
                ('items_total_price_without_discount', models.FloatField(default=0)),
                ('items_total_price', models.FloatField(default=0)),
                ('promo_deductable_amount', models.FloatField(default=0)),
                ('order_total_discount_amount', models.FloatField(default=0)),
                ('order_net_amount', models.FloatField(default=0)),
                ('order_due_amount', models.FloatField(default=0)),
                ('order_paid_amount', models.FloatField(blank=True, null=True)),
                ('order_net_amount_without_shipping', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_value', models.FloatField(default=0)),
                ('discount_type', models.CharField(blank=True, choices=[('flat', 'flat'), ('percentage', 'percentage')], max_length=10, null=True)),
                ('campaign_member_discount', models.FloatField(default=0)),
                ('deal_of_the_week_discount', models.FloatField(default=0)),
                ('total_discount', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('additional_charge', models.FloatField(default=0)),
                ('shipping_charge', models.FloatField(default=0)),
                ('total_weight', models.FloatField(help_text='Product Variant Weight * Quantity')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned')], max_length=20, null=True)),
                ('commission_calculation', models.TextField(blank=True, default='No calculation', null=True)),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_voucher', models.CharField(blank=True, max_length=150, null=True)),
                ('paid_amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'order_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
