# Generated by Django 4.2.11 on 2024-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], max_length=10, null=True),
        ),
    ]
