# Generated by Django 3.1.4 on 2024-09-19 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('discount_type', models.CharField(choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], max_length=20)),
                ('min_discount', models.FloatField(default=0)),
                ('max_discount', models.FloatField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], max_length=12)),
                ('discount_value', models.FloatField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dealoftheweeks', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_dealoftheweeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deal_of_the_weeks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('select', 'select'), ('flat', 'flat'), ('percentage', 'percentage')], max_length=10)),
                ('discount_value', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaignmembers', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_campaignmembers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dealoftheweek',
            index=models.Index(fields=['-created_at'], name='deal_of_the_created_0cb1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='dealoftheweek',
            index=models.Index(fields=['is_active'], name='deal_of_the_is_acti_f9f4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['-created_at'], name='campaign_me_created_d3e0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['is_active'], name='campaign_me_is_acti_2554dd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='campaigns_created_163163_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='campaigns_is_acti_6c57d0_idx'),
        ),
    ]
