# Generated by Django 3.1.4 on 2025-03-05 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoftheweek',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dealoftheweeks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealoftheweek',
            name='product_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='dealoftheweek',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_dealoftheweeks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmember',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='campaignmember',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaignmembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmember',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='campaignmember',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_campaignmembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dealoftheweek',
            index=models.Index(fields=['-created_at'], name='deal_of_the_created_0cb1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='dealoftheweek',
            index=models.Index(fields=['is_active'], name='deal_of_the_is_acti_f9f4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['-created_at'], name='campaign_me_created_d3e0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['is_active'], name='campaign_me_is_acti_2554dd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='campaigns_created_163163_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='campaigns_is_acti_6c57d0_idx'),
        ),
    ]
